// Generated by CoffeeScript 1.3.3
(function() {
  var $,
    __slice = [].slice;

  $ = jQuery;

  $.PowerPlugin = (function() {

    PowerPlugin.prototype.defaults = {};

    PowerPlugin.prototype.events = {};

    PowerPlugin.setup = function(pluginName) {
      var that;
      that = this;
      return $.fn[pluginName] = function(options) {
        new that(this, options);
        return this;
      };
    };

    function PowerPlugin(element, options) {
      if (options == null) {
        options = {};
      }
      this.element = this.el = $(element);
      this.setOptions(options);
      this.initialize();
      this.bindEvents();
    }

    PowerPlugin.prototype.setOptions = function(options) {
      return this.options = $.extend(true, {}, this.defaults, options);
    };

    PowerPlugin.prototype.initialize = function() {};

    PowerPlugin.prototype.bindEvents = function() {
      var callback, event, _ref, _results;
      _ref = this.events;
      _results = [];
      for (event in _ref) {
        callback = _ref[event];
        _results.push(this.bindEvent(event, callback));
      }
      return _results;
    };

    PowerPlugin.prototype.bindEvent = function(event, callback) {
      var keys, selector, trigger;
      keys = event.split(" ");
      trigger = keys.shift();
      selector = keys.join(" ");
      if (selector) {
        return $(this.element).on(trigger, selector, this.eventCallback(callback));
      } else {
        return $(this.element).on(trigger, this.eventCallback(callback));
      }
    };

    PowerPlugin.prototype.eventCallback = function(callback) {
      var that;
      that = this;
      return function() {
        var args;
        args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        return that[callback].apply(that, args);
      };
    };

    return PowerPlugin;

  })();

}).call(this);
